# ==============================================================================
# The [project] table defined by Official python.org
#
# Read: https://packaging.python.org/en/latest/guides/writing-pyproject-toml/
# ==============================================================================
[project]
name = "delta_lake_and_polars_basic"
version = "0.1.1"
description = "Delta Lake and Polars POC"
license = "MIT"
keywords = []
readme = "README.rst"
requires-python = ">=3.12,<4.0"

# ------------------------------------------------------------------------------
# Core Dependencies
# ------------------------------------------------------------------------------
dependencies = [
    "boto3>=1.42.95,<2.0.0",
    "boto3-stubs[s3]>=1.42.95,<2.0.0",
    "boto-session-manager>=1.8.1,<2.0.0",
    "s3pathlib>=2.3.6,<3.0.0",
    "polars>=1.39.3,<1.40.0",
    "deltalake>=1.5.1,<1.6.0",
]

# ------------------------------------------------------------------------------
# Optional dependency that can be used in ``pip install ${your_project_name}[${feature_name}]``
# Sometime this is also called "extras"
# Read: https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#dependencies-optional-dependencies
#
# IMPORTANT: all optional dependencies has to be compatible with the "requires-python" field
# ------------------------------------------------------------------------------
[project.optional-dependencies]

# ------------------------------------------------------------------------------
# Local Development dependenceies
# ------------------------------------------------------------------------------
dev = [
    "rich>=13.8.1,<14.0.0", # pretty print
]

# ------------------------------------------------------------------------------
# (Unit/Coverage/Integration/Load) Test dependenceies
# ------------------------------------------------------------------------------
test = [
    "pytest>=8.2.2,<9.0.0", # Testing framework
    "pytest-cov>=6.0.0,<7.0.0", # Coverage reporting
]

# For command line interface, read: https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#creating-executable-scripts
[project.scripts]

[tool.setuptools.packages.find]
where = ["."]
include = [
    "delta_lake_and_polars_basic*"
]
exclude = [
    "delta_lake_and_polars_basic.tests",
    "delta_lake_and_polars_basic.tests.*",
    "delta_lake_and_polars_basic.docs",
    "delta_lake_and_polars_basic.docs.*",
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
